spring:
  application:
    name: "Sample Service Consumer"

gateway:
  employee:
    baseUrl: "http://localhost:8082/api"

logging.level:
  org.springframework.cloud.sleuth: DEBUG

spring.zipkin.baseUrl: http://localhost:9411
spring.sleuth.sampler.percentage: 1.0