spring:
  application:
    name: "Sample Service Consumer"
  boot:
    admin:
      client:
        url: http://localhost:8080
        health-url: http://localhost:8082/actuator/health
gateway:
  employee:
    baseUrl: "http://localhost:8082/api"

server.port: 8082

logging.level:
  org.springframework.cloud.sleuth: DEBUG

#spring.zipkin.baseUrl: http://localhost:9411
#spring.sleuth.sampler.percentage: 1.0