spring:
  application:
    name: "Sample hazelcast example"

crnk:
  domainName: http://localhost:8082
  pathPrefix: /api

cxf.path: "/api"

server.port: 8082

logging.level:
  org.springframework.cloud.sleuth: DEBUG

spring.zipkin.baseUrl: http://localhost:9411
spring.sleuth.sampler.percentage: 1.0